spring:
  application:
    name: "auth-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/innotech
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  hibernate:
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
  server:
    port: 8080

auth:
  secret: 0J/QvtGP0LLQuNC70YHRjywg0LfQvdCw0YfQuNGCLCDQsiDQl9C+0L3QtSDQp9C10YDQvdGL0Lkg0KHRgtCw0LvQutC10YAuINCaINC70LDQs9C10YDRjiDQvdC+0YfRjNGOINC/0L7QstCw0LTQuNC70YHRjyDRhdC+0LTQuNGC0YwuINCYINGC0LDQvCDRgdGD0LXRgiDRgNGD0LrRgyDQsiDQv9Cw0LvQsNGC0LrRgyDQuCDQs9C+0LLQvtGA0LjRgjoK4oCUINCS0LLQsNC00LjQuNC40YfQutC4INC/0LDQv9C40LjQuNC40YLRjCwg4oCUINCwINC10YHQu9C4INC90LUg0LTQsNGI0Ywg0YXQu9C10LHQvdGD0YLRjCDQuNC3INGE0LvRj9C20LrQuCDQuNC70Lgg0L3QsNGA0YPQttGDINC/0L7Qu9C10LfQtdGI0Ywg4oCUINC/0YDQuNGI0LjQsdC10YIhCtCQINGA0LDQtyDQvNGD0LbQuNC6INC+0LTQuNC9INGA0LXRiNC40Lsg0L/QvtGI0YPRgtC40YLRjDog0LLRi9C70LXQtyDRgtC40YXQviDQuNC3INC/0LDQu9Cw0YLQutC4LCDQvdCw0LTQtdC7INC60L7QttCw0L3Rg9GOINC/0LXRgNGH0LDRgtC60YMsINC4INC/0L7Qu9C10Lcg0Log0YHQvtGB0LXQtNGP0Lwg0LIg0L/QsNC70LDRgtC60YMuINCf0L7Qu9C10LcsINC30L3QsNGH0LjRgiwg0Lgg0L/QvtC/0YDQvtGJ0LDQudC90LjRh9Cw0LXRgiDQttCw0LvQvtGB0YLQvdC+OgrigJQg0JLQsNC00LjQuNC40YfQutC4LCDQstCw0LTQuNC40LjRh9C60Lgg0L/QsNC/0LjRgtGM4oCmCtCQINGC0YPRgiDQuNC3INC/0LDQu9Cw0YLQutC4INC90LDQstGB0YLRgNC10YfRgyDQstGL0YHQvtCy0YvQstCw0LXRgtGB0Y8g0YDRg9C60LAg0Lgg0LfQsCDQs9C+0YDQu9C+INC10LPQvuKApiDQptCw0L8hINCYINGC0LDQutC+0Lkg0YHQuNC/0LvRi9C5INCz0L7Qu9C+0YHQvtC6INC+0YLQt9GL0LLQsNC10YLRgdGPINGC0LjRhdC+0L3RjNC60L46CuKAlCDQkCDRgtC10LHQtSDQvNC+0Y8g0LLQvtC00LjRh9C60LAg0JfQkNCn0JXQnCDQvdGD0LbQvdCwPyE=
  auth-token:
    duration: 100m
  refresh-token:
    duration: 100m


logging:
  level:
    root: info
    org:
      hibernate:
        type: info
