spring:
  application:
    name: "auth-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/innotech
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  hibernate:
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
  server:
    port: 8080

auth:
  secret: secretkey
  auth-token:
    duration: 1m
  refresh-token:
    duration: 10m


logging:
  level:
    root: info
    org:
      hibernate:
        type: info
      springframework:
        data:
          r2dbc: debug